In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
# (My Code from ITMD 522 - HW#2)

# import pandas as pd.
import pandas as pd
import numpy as np
from pathlib import Path

# Folder path: '/Users/harshpatel/Desktop/MS-ITM/ITMD 524/project_dataset'
folder_path = Path('/Users/harshpatel/Desktop/MS-ITM/ITMD 524/project_dataset')  

# Read the excel file and specific 'Data' spreadsheet from CSV file. Get all CSV files in the folder.
# pandas.read_csv(filepath_or_buffer, *, sep=<no_default>, delimiter=None, header='infer', names=<no_default>, index_col=None, usecols=None, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=<no_default>, skip_blank_lines=True, parse_dates=None, infer_datetime_format=<no_default>, keep_date_col=<no_default>, date_parser=<no_default>, date_format=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal='.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors='strict', dialect=None, on_bad_lines='error', delim_whitespace=<no_default>, low_memory=True, memory_map=False, float_precision=None, storage_options=None, dtype_backend=<no_default>)
# csv_files = [f for f in folder_path.glob('*.csv') if 'Small' in f.name]
csv_files = [f for f in folder_path.glob('*.csv') if 'Small' in f.name]

# To assign names for each datafile as a dataframe.
for file in csv_files:
    var_name = file.stem.replace(" ", "_").replace("-", "_")
    globals()[var_name] = pd.read_csv(file)
    print(f"Loaded: {var_name} (shape: {globals()[var_name].shape})")

Loaded: HI_Small_Trans (shape: (5078345, 11))
Loaded: LI_Small_Trans (shape: (6924049, 11))

# HI_Small_Trans dataset.

In [3]:
LI_Small_Trans

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,2022/09/01 00:08,11,8000ECA90,11,8000ECA90,3.195403e+06,US Dollar,3.195403e+06,US Dollar,Reinvestment,0
1,2022/09/01 00:21,3402,80021DAD0,3402,80021DAD0,1.858960e+03,US Dollar,1.858960e+03,US Dollar,Reinvestment,0
2,2022/09/01 00:00,11,8000ECA90,1120,8006AA910,5.925710e+05,US Dollar,5.925710e+05,US Dollar,Cheque,0
3,2022/09/01 00:16,3814,8006AD080,3814,8006AD080,1.232000e+01,US Dollar,1.232000e+01,US Dollar,Reinvestment,0
4,2022/09/01 00:00,20,8006AD530,20,8006AD530,2.941560e+03,US Dollar,2.941560e+03,US Dollar,Reinvestment,0
...,...,...,...,...,...,...,...,...,...,...,...
6924044,2022/09/10 23:39,71696,81B2518F1,71528,81C0482E1,3.346900e-02,Bitcoin,3.346900e-02,Bitcoin,Bitcoin,0
6924045,2022/09/10 23:48,271241,81B567481,173457,81C0DA751,1.313000e-03,Bitcoin,1.313000e-03,Bitcoin,Bitcoin,0
6924046,2022/09/10 23:50,271241,81B567481,173457,81C0DA751,1.305800e-02,Bitcoin,1.305800e-02,Bitcoin,Bitcoin,0
6924047,2022/09/10 23:57,170558,81A2206B1,275798,81C1D5CA1,4.145370e-01,Bitcoin,4.145370e-01,Bitcoin,Bitcoin,0
6924048,2022/09/10 23:31,170558,81A2206B1,275798,81C1D5CA1,3.427700e-02,Bitcoin,3.427700e-02,Bitcoin,Bitcoin,0

# LI_Small_Trans dataset.

In [4]:
HI_Small_Trans

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.340000,US Dollar,3697.340000,US Dollar,Reinvestment,0
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.010000,US Dollar,0.010000,US Dollar,Cheque,0
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.570000,US Dollar,14675.570000,US Dollar,Reinvestment,0
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.970000,US Dollar,2806.970000,US Dollar,Reinvestment,0
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.970000,US Dollar,36682.970000,US Dollar,Reinvestment,0
...,...,...,...,...,...,...,...,...,...,...,...
5078340,2022/09/10 23:57,54219,8148A6631,256398,8148A8711,0.154978,Bitcoin,0.154978,Bitcoin,Bitcoin,0
5078341,2022/09/10 23:35,15,8148A8671,256398,8148A8711,0.108128,Bitcoin,0.108128,Bitcoin,Bitcoin,0
5078342,2022/09/10 23:52,154365,8148A6771,256398,8148A8711,0.004988,Bitcoin,0.004988,Bitcoin,Bitcoin,0
5078343,2022/09/10 23:46,256398,8148A6311,256398,8148A8711,0.038417,Bitcoin,0.038417,Bitcoin,Bitcoin,0
5078344,2022/09/10 23:37,154518,8148A6091,256398,8148A8711,0.281983,Bitcoin,0.281983,Bitcoin,Bitcoin,0

# Merge two dataset.

In [5]:
merged_Small_df = pd.concat([LI_Small_Trans, HI_Small_Trans], ignore_index=True)
display(merged_Small_df)
display(merged_Small_df.info())
display(merged_Small_df.nunique())
value_counts = merged_Small_df['Is Laundering'].value_counts()
print(value_counts)

merged_Small_df = merged_Small_df[merged_Small_df['Receiving Currency'] == 'Bitcoin']
merged_Small_df

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,2022/09/01 00:08,11,8000ECA90,11,8000ECA90,3.195403e+06,US Dollar,3.195403e+06,US Dollar,Reinvestment,0
1,2022/09/01 00:21,3402,80021DAD0,3402,80021DAD0,1.858960e+03,US Dollar,1.858960e+03,US Dollar,Reinvestment,0
2,2022/09/01 00:00,11,8000ECA90,1120,8006AA910,5.925710e+05,US Dollar,5.925710e+05,US Dollar,Cheque,0
3,2022/09/01 00:16,3814,8006AD080,3814,8006AD080,1.232000e+01,US Dollar,1.232000e+01,US Dollar,Reinvestment,0
4,2022/09/01 00:00,20,8006AD530,20,8006AD530,2.941560e+03,US Dollar,2.941560e+03,US Dollar,Reinvestment,0
...,...,...,...,...,...,...,...,...,...,...,...
12002389,2022/09/10 23:57,54219,8148A6631,256398,8148A8711,1.549780e-01,Bitcoin,1.549780e-01,Bitcoin,Bitcoin,0
12002390,2022/09/10 23:35,15,8148A8671,256398,8148A8711,1.081280e-01,Bitcoin,1.081280e-01,Bitcoin,Bitcoin,0
12002391,2022/09/10 23:52,154365,8148A6771,256398,8148A8711,4.988000e-03,Bitcoin,4.988000e-03,Bitcoin,Bitcoin,0
12002392,2022/09/10 23:46,256398,8148A6311,256398,8148A8711,3.841700e-02,Bitcoin,3.841700e-02,Bitcoin,Bitcoin,0
12002393,2022/09/10 23:37,154518,8148A6091,256398,8148A8711,2.819830e-01,Bitcoin,2.819830e-01,Bitcoin,Bitcoin,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12002394 entries, 0 to 12002393
Data columns (total 11 columns):
 #   Column              Dtype
---  ------              -----
 0   Timestamp           object
 1   From Bank           int64
 2   Account             object
 3   To Bank             int64
 4   Account.1           object
 5   Amount Received     float64
 6   Receiving Currency  object
 7   Amount Paid         float64
 8   Payment Currency    object
 9   Payment Format      object
 10  Is Laundering       int64
dtypes: float64(2), int64(3), object(6)
memory usage: 1007.3+ MB

None

Timestamp               15133
From Bank               57222
Account               1166980
To Bank                 33608
Account.1              988911
Amount Received       1835635
Receiving Currency         15
Amount Paid           1850741
Payment Currency           15
Payment Format              7
Is Laundering               2
dtype: int64

0    11993652
1        8742
Name: Is Laundering, dtype: int64

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
3461,2022/09/01 00:07,1,8001D8BA1,20,80065EFC1,3258.136148,Bitcoin,3258.136148,Bitcoin,Bitcoin,0
14822,2022/09/01 00:19,2692,80129D831,3440,8017A9D11,11.251933,Bitcoin,11.251933,Bitcoin,Bitcoin,0
15936,2022/09/01 00:08,11701,800A61DE1,13210,801AFC811,0.245199,Bitcoin,0.245199,Bitcoin,Bitcoin,0
25647,2022/09/01 00:15,2860,800B9CD51,18081,80388BE21,0.479295,Bitcoin,0.479295,Bitcoin,Bitcoin,0
34575,2022/09/01 00:11,25242,802594F51,4894,8057DC7A1,0.265803,Bitcoin,0.265803,Bitcoin,Bitcoin,0
...,...,...,...,...,...,...,...,...,...,...,...
12002389,2022/09/10 23:57,54219,8148A6631,256398,8148A8711,0.154978,Bitcoin,0.154978,Bitcoin,Bitcoin,0
12002390,2022/09/10 23:35,15,8148A8671,256398,8148A8711,0.108128,Bitcoin,0.108128,Bitcoin,Bitcoin,0
12002391,2022/09/10 23:52,154365,8148A6771,256398,8148A8711,0.004988,Bitcoin,0.004988,Bitcoin,Bitcoin,0
12002392,2022/09/10 23:46,256398,8148A6311,256398,8148A8711,0.038417,Bitcoin,0.038417,Bitcoin,Bitcoin,0
12002393,2022/09/10 23:37,154518,8148A6091,256398,8148A8711,0.281983,Bitcoin,0.281983,Bitcoin,Bitcoin,0

# X independent and Y dependent variable.

In [6]:
# Define a function to extract last 4 characters from account (as string)
def last_4_digits(val):
    if pd.isna(val):
        return 'UNK'  # For missing values
    return str(val)[-4:]

# Apply it to high-cardinality object columns
merged_Small_df['Account_Grouped'] = merged_Small_df['Account'].apply(last_4_digits)
merged_Small_df['Account1_Grouped'] = merged_Small_df['Account.1'].apply(last_4_digits)

X = merged_Small_df.drop(columns='Is Laundering')
y = merged_Small_df['Is Laundering']

print("X:\n")
display(X)

print("Y:\n")
display(y)

X:

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Account_Grouped,Account1_Grouped
3461,2022/09/01 00:07,1,8001D8BA1,20,80065EFC1,3258.136148,Bitcoin,3258.136148,Bitcoin,Bitcoin,8BA1,EFC1
14822,2022/09/01 00:19,2692,80129D831,3440,8017A9D11,11.251933,Bitcoin,11.251933,Bitcoin,Bitcoin,D831,9D11
15936,2022/09/01 00:08,11701,800A61DE1,13210,801AFC811,0.245199,Bitcoin,0.245199,Bitcoin,Bitcoin,1DE1,C811
25647,2022/09/01 00:15,2860,800B9CD51,18081,80388BE21,0.479295,Bitcoin,0.479295,Bitcoin,Bitcoin,CD51,BE21
34575,2022/09/01 00:11,25242,802594F51,4894,8057DC7A1,0.265803,Bitcoin,0.265803,Bitcoin,Bitcoin,4F51,C7A1
...,...,...,...,...,...,...,...,...,...,...,...,...
12002389,2022/09/10 23:57,54219,8148A6631,256398,8148A8711,0.154978,Bitcoin,0.154978,Bitcoin,Bitcoin,6631,8711
12002390,2022/09/10 23:35,15,8148A8671,256398,8148A8711,0.108128,Bitcoin,0.108128,Bitcoin,Bitcoin,8671,8711
12002391,2022/09/10 23:52,154365,8148A6771,256398,8148A8711,0.004988,Bitcoin,0.004988,Bitcoin,Bitcoin,6771,8711
12002392,2022/09/10 23:46,256398,8148A6311,256398,8148A8711,0.038417,Bitcoin,0.038417,Bitcoin,Bitcoin,6311,8711
12002393,2022/09/10 23:37,154518,8148A6091,256398,8148A8711,0.281983,Bitcoin,0.281983,Bitcoin,Bitcoin,6091,8711

Y:

3461        0
14822       0
15936       0
25647       0
34575       0
           ..
12002389    0
12002390    0
12002391    0
12002392    0
12002393    0
Name: Is Laundering, Length: 461347, dtype: int64

# Things I did for X.

- Convert Timestamp into columns like i.e., {hour, day, weekday, and month}.
- For Account_Grouped and Account1_Grouped columns,
    - Extract first two letters (if present)
    - Collect the digits at the end (whatever part is numeric)

In [7]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import re

# Drop redundant columns
X = X.drop(columns=['Account', 'Account.1'])

# Convert string to datetime
X['timestamp_column_name'] = pd.to_datetime(X['Timestamp'])

# Extract datetime features
X['hour'] = X['timestamp_column_name'].dt.hour
X['day'] = X['timestamp_column_name'].dt.day
X['weekday'] = X['timestamp_column_name'].dt.weekday
X['month'] = X['timestamp_column_name'].dt.month

X = X.drop(['Timestamp'], axis=1)

# One-hot encode selected categorical columns
categorical_cols = ['Receiving Currency', 'Payment Currency', 'Payment Format']

encoder = OneHotEncoder(sparse=False, handle_unknown='ignore')
encoded_array = encoder.fit_transform(X[categorical_cols])

encoded_df = pd.DataFrame(
    encoded_array,
    columns=encoder.get_feature_names_out(categorical_cols),
    index=X.index
)

X = pd.concat([X.drop(columns=categorical_cols), encoded_df], axis=1)

def fast_encode_account_grouped(df, column_name, prefix):
    col = df[column_name].astype(str).str.strip()

    # Extract first two letters
    letters = col.str.extract(r'([A-Za-z])?([A-Za-z])?')
    digits = col.str.extract(r'(\d+)')

    l1 = letters[0].str.upper().apply(lambda x: ord(x) - ord('A') if pd.notnull(x) else -1)
    l2 = letters[1].str.upper().apply(lambda x: ord(x) - ord('A') if pd.notnull(x) else -1)
    num = digits[0].fillna(-1).astype(int)

    return pd.DataFrame({
        f'{prefix}_L1': l1,
        f'{prefix}_L2': l2,
        f'{prefix}_Num': num
    }, index=df.index)

# Apply vectorized encoding
X = pd.concat([
    X,
    fast_encode_account_grouped(X, 'Account_Grouped', 'AG'),
    fast_encode_account_grouped(X, 'Account1_Grouped', 'AG1')
], axis=1)

X.drop(columns=['Account_Grouped', 'Account1_Grouped'], inplace=True)
X

/usr/local/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

,From Bank,To Bank,Amount Received,Amount Paid,timestamp_column_name,hour,day,weekday,month,Receiving Currency_Bitcoin,...,Payment Currency_Yuan,Payment Format_ACH,Payment Format_Bitcoin,Payment Format_Wire,AG_L1,AG_L2,AG_Num,AG1_L1,AG1_L2,AG1_Num
3461,1,20,3258.136148,3258.136148,2022-09-01 00:07:00,0,1,3,9,1.0,...,0.0,0.0,1.0,0.0,-1,-1,8,4,5,1
14822,2692,3440,11.251933,11.251933,2022-09-01 00:19:00,0,1,3,9,1.0,...,0.0,0.0,1.0,0.0,3,-1,831,-1,-1,9
15936,11701,13210,0.245199,0.245199,2022-09-01 00:08:00,0,1,3,9,1.0,...,0.0,0.0,1.0,0.0,-1,-1,1,2,-1,811
25647,2860,18081,0.479295,0.479295,2022-09-01 00:15:00,0,1,3,9,1.0,...,0.0,0.0,1.0,0.0,2,3,51,1,4,21
34575,25242,4894,0.265803,0.265803,2022-09-01 00:11:00,0,1,3,9,1.0,...,0.0,0.0,1.0,0.0,-1,-1,4,2,-1,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12002389,54219,256398,0.154978,0.154978,2022-09-10 23:57:00,23,10,5,9,1.0,...,0.0,0.0,1.0,0.0,-1,-1,6631,-1,-1,8711
12002390,15,256398,0.108128,0.108128,2022-09-10 23:35:00,23,10,5,9,1.0,...,0.0,0.0,1.0,0.0,-1,-1,8671,-1,-1,8711
12002391,154365,256398,0.004988,0.004988,2022-09-10 23:52:00,23,10,5,9,1.0,...,0.0,0.0,1.0,0.0,-1,-1,6771,-1,-1,8711
12002392,256398,256398,0.038417,0.038417,2022-09-10 23:46:00,23,10,5,9,1.0,...,0.0,0.0,1.0,0.0,-1,-1,6311,-1,-1,8711
12002393,154518,256398,0.281983,0.281983,2022-09-10 23:37:00,23,10,5,9,1.0,...,0.0,0.0,1.0,0.0,-1,-1,6091,-1,-1,8711

In [8]:
y

3461        0
14822       0
15936       0
25647       0
34575       0
           ..
12002389    0
12002390    0
12002391    0
12002392    0
12002393    0
Name: Is Laundering, Length: 461347, dtype: int64

# Now, Oversample (SMOTE) and Undersample Majority Class.

- We will get new balanced data -- X and y.

In [9]:
# Identify datetime columns
datetime_cols = X.select_dtypes(include=['datetime64']).columns
print(datetime_cols)

# Convert them into numeric features (like year, month, etc.)
for col in datetime_cols:
    X[f'{col}_year'] = X[col].dt.year
    X[f'{col}_month'] = X[col].dt.month
    X[f'{col}_day'] = X[col].dt.day
    X[f'{col}_minute'] = X[col].dt.minute
    # drop original datetime column
    X.drop(columns=col, inplace=True)
    
X

Index(['timestamp_column_name'], dtype='object')

,From Bank,To Bank,Amount Received,Amount Paid,hour,day,weekday,month,Receiving Currency_Bitcoin,Payment Currency_Australian Dollar,...,AG_L1,AG_L2,AG_Num,AG1_L1,AG1_L2,AG1_Num,timestamp_column_name_year,timestamp_column_name_month,timestamp_column_name_day,timestamp_column_name_minute
3461,1,20,3258.136148,3258.136148,0,1,3,9,1.0,0.0,...,-1,-1,8,4,5,1,2022,9,1,7
14822,2692,3440,11.251933,11.251933,0,1,3,9,1.0,0.0,...,3,-1,831,-1,-1,9,2022,9,1,19
15936,11701,13210,0.245199,0.245199,0,1,3,9,1.0,0.0,...,-1,-1,1,2,-1,811,2022,9,1,8
25647,2860,18081,0.479295,0.479295,0,1,3,9,1.0,0.0,...,2,3,51,1,4,21,2022,9,1,15
34575,25242,4894,0.265803,0.265803,0,1,3,9,1.0,0.0,...,-1,-1,4,2,-1,7,2022,9,1,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12002389,54219,256398,0.154978,0.154978,23,10,5,9,1.0,0.0,...,-1,-1,6631,-1,-1,8711,2022,9,10,57
12002390,15,256398,0.108128,0.108128,23,10,5,9,1.0,0.0,...,-1,-1,8671,-1,-1,8711,2022,9,10,35
12002391,154365,256398,0.004988,0.004988,23,10,5,9,1.0,0.0,...,-1,-1,6771,-1,-1,8711,2022,9,10,52
12002392,256398,256398,0.038417,0.038417,23,10,5,9,1.0,0.0,...,-1,-1,6311,-1,-1,8711,2022,9,10,46
12002393,154518,256398,0.281983,0.281983,23,10,5,9,1.0,0.0,...,-1,-1,6091,-1,-1,8711,2022,9,10,37

In [10]:
print(X.dtypes)

# Normalization on X
# y is already normalized.
from sklearn.preprocessing import MinMaxScaler

original_columns = X.columns

scaler = MinMaxScaler()
X = scaler.fit_transform(X)  # Returns a NumPy array

# Optionally convert back to DataFrame (to keep column names)
X = pd.DataFrame(X, columns=original_columns)

X

From Bank                               int64
To Bank                                 int64
Amount Received                       float64
Amount Paid                           float64
hour                                    int64
day                                     int64
weekday                                 int64
month                                   int64
Receiving Currency_Bitcoin            float64
Payment Currency_Australian Dollar    float64
Payment Currency_Bitcoin              float64
Payment Currency_Brazil Real          float64
Payment Currency_Canadian Dollar      float64
Payment Currency_Euro                 float64
Payment Currency_Mexican Peso         float64
Payment Currency_Ruble                float64
Payment Currency_Rupee                float64
Payment Currency_Saudi Riyal          float64
Payment Currency_Shekel               float64
Payment Currency_Swiss Franc          float64
Payment Currency_UK Pound             float64
Payment Currency_US Dollar            float64
Payment Currency_Yen                  float64
Payment Currency_Yuan                 float64
Payment Format_ACH                    float64
Payment Format_Bitcoin                float64
Payment Format_Wire                   float64
AG_L1                                   int64
AG_L2                                   int64
AG_Num                                  int64
AG1_L1                                  int64
AG1_L2                                  int64
AG1_Num                                 int64
timestamp_column_name_year              int64
timestamp_column_name_month             int64
timestamp_column_name_day               int64
timestamp_column_name_minute            int64
dtype: object

,From Bank,To Bank,Amount Received,Amount Paid,hour,day,weekday,month,Receiving Currency_Bitcoin,Payment Currency_Australian Dollar,...,AG_L1,AG_L2,AG_Num,AG1_L1,AG1_L2,AG1_Num,timestamp_column_name_year,timestamp_column_name_month,timestamp_column_name_day,timestamp_column_name_minute
0,0.000003,0.000053,5.288967e-03,5.288967e-03,0.0,0.0,0.500000,0.0,0.0,0.0,...,0.000000,0.000000,0.000801,0.833333,1.000000,0.000100,0.0,0.0,0.0,0.118644
1,0.007141,0.009125,1.826538e-05,1.826538e-05,0.0,0.0,0.500000,0.0,0.0,0.0,...,0.666667,0.000000,0.083175,0.000000,0.000000,0.000901,0.0,0.0,0.0,0.322034
2,0.031040,0.035043,3.980325e-07,3.980325e-07,0.0,0.0,0.500000,0.0,0.0,0.0,...,0.000000,0.000000,0.000100,0.500000,0.000000,0.081173,0.0,0.0,0.0,0.135593
3,0.007587,0.047964,7.780431e-07,7.780431e-07,0.0,0.0,0.500000,0.0,0.0,0.0,...,0.500000,0.666667,0.005105,0.333333,0.833333,0.002102,0.0,0.0,0.0,0.254237
4,0.066961,0.012983,4.314792e-07,4.314792e-07,0.0,0.0,0.500000,0.0,0.0,0.0,...,0.000000,0.000000,0.000400,0.500000,0.000000,0.000701,0.0,0.0,0.0,0.186441
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
461342,0.143830,0.680160,2.515758e-07,2.515758e-07,1.0,1.0,0.833333,0.0,0.0,0.0,...,0.000000,0.000000,0.663697,0.000000,0.000000,0.871885,0.0,0.0,1.0,0.966102
461343,0.000040,0.680160,1.755237e-07,1.755237e-07,1.0,1.0,0.833333,0.0,0.0,0.0,...,0.000000,0.000000,0.867881,0.000000,0.000000,0.871885,0.0,0.0,1.0,0.593220
461344,0.409492,0.680160,8.095451e-09,8.095451e-09,1.0,1.0,0.833333,0.0,0.0,0.0,...,0.000000,0.000000,0.677710,0.000000,0.000000,0.871885,0.0,0.0,1.0,0.881356
461345,0.680160,0.680160,6.236111e-08,6.236111e-08,1.0,1.0,0.833333,0.0,0.0,0.0,...,0.000000,0.000000,0.631669,0.000000,0.000000,0.871885,0.0,0.0,1.0,0.779661
461346,0.409898,0.680160,4.577444e-07,4.577444e-07,1.0,1.0,0.833333,0.0,0.0,0.0,...,0.000000,0.000000,0.609649,0.000000,0.000000,0.871885,0.0,0.0,1.0,0.627119

# Split the dataset.

In [11]:
from sklearn.model_selection import train_test_split

y = y.reset_index(drop=True)

# Source: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
# sklearn.model_selection.train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)
# Example: X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, # X scalered data.
                                                    y, # y
                                                    test_size=0.25, # test_size : float or int, default=None
                                                    random_state=42, # random_state : int, RandomState instance or None, default=None
                                                    shuffle=True, # shuffle : bool, default=True
                                                    stratify=y) # stratify : array-like, default=None

# Sort the index of X_train
X_train = X_train.sort_index()

# Sort the index of X_test
X_test = X_test.sort_index()

# Sort the index of y_train
y_train = y_train.sort_index()

# Sort the index of y_test
y_test = y_test.sort_index()

In [12]:
# Show the training dataset. X_train and y_train.
display("The predict_cols_scaled_df_X_train dataset: \n", X_train)
# y_train
display("\n\nThe predict_cols_scaled_df_y_train dataset: \n", y_train)
y_train.value_counts()

'The predict_cols_scaled_df_X_train dataset: \n'

,From Bank,To Bank,Amount Received,Amount Paid,hour,day,weekday,month,Receiving Currency_Bitcoin,Payment Currency_Australian Dollar,...,AG_L1,AG_L2,AG_Num,AG1_L1,AG1_L2,AG1_Num,timestamp_column_name_year,timestamp_column_name_month,timestamp_column_name_day,timestamp_column_name_minute
0,0.000003,0.000053,5.288967e-03,5.288967e-03,0.0,0.0,0.500000,0.0,0.0,0.0,...,0.000000,0.000000,0.000801,0.833333,1.000000,0.000100,0.0,0.0,0.0,0.118644
1,0.007141,0.009125,1.826538e-05,1.826538e-05,0.0,0.0,0.500000,0.0,0.0,0.0,...,0.666667,0.000000,0.083175,0.000000,0.000000,0.000901,0.0,0.0,0.0,0.322034
2,0.031040,0.035043,3.980325e-07,3.980325e-07,0.0,0.0,0.500000,0.0,0.0,0.0,...,0.000000,0.000000,0.000100,0.500000,0.000000,0.081173,0.0,0.0,0.0,0.135593
3,0.007587,0.047964,7.780431e-07,7.780431e-07,0.0,0.0,0.500000,0.0,0.0,0.0,...,0.500000,0.666667,0.005105,0.333333,0.833333,0.002102,0.0,0.0,0.0,0.254237
4,0.066961,0.012983,4.314792e-07,4.314792e-07,0.0,0.0,0.500000,0.0,0.0,0.0,...,0.000000,0.000000,0.000400,0.500000,0.000000,0.000701,0.0,0.0,0.0,0.186441
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
461342,0.143830,0.680160,2.515758e-07,2.515758e-07,1.0,1.0,0.833333,0.0,0.0,0.0,...,0.000000,0.000000,0.663697,0.000000,0.000000,0.871885,0.0,0.0,1.0,0.966102
461343,0.000040,0.680160,1.755237e-07,1.755237e-07,1.0,1.0,0.833333,0.0,0.0,0.0,...,0.000000,0.000000,0.867881,0.000000,0.000000,0.871885,0.0,0.0,1.0,0.593220
461344,0.409492,0.680160,8.095451e-09,8.095451e-09,1.0,1.0,0.833333,0.0,0.0,0.0,...,0.000000,0.000000,0.677710,0.000000,0.000000,0.871885,0.0,0.0,1.0,0.881356
461345,0.680160,0.680160,6.236111e-08,6.236111e-08,1.0,1.0,0.833333,0.0,0.0,0.0,...,0.000000,0.000000,0.631669,0.000000,0.000000,0.871885,0.0,0.0,1.0,0.779661
461346,0.409898,0.680160,4.577444e-07,4.577444e-07,1.0,1.0,0.833333,0.0,0.0,0.0,...,0.000000,0.000000,0.609649,0.000000,0.000000,0.871885,0.0,0.0,1.0,0.627119

'\n\nThe predict_cols_scaled_df_y_train dataset: \n'

0         0
1         0
2         0
3         0
4         0
         ..
461342    0
461343    0
461344    0
461345    0
461346    0
Name: Is Laundering, Length: 346010, dtype: int64

0    345886
1       124
Name: Is Laundering, dtype: int64

In [13]:
# Show the testing dataset. X_test and y_test.
display("The predict_cols_scaled_df_X_test dataset: \n", X_test)
# y_test
display("\n\nThe predict_cols_scaled_df_y_test dataset: \n", y_test)
y_test.value_counts()

'The predict_cols_scaled_df_X_test dataset: \n'

,From Bank,To Bank,Amount Received,Amount Paid,hour,day,weekday,month,Receiving Currency_Bitcoin,Payment Currency_Australian Dollar,...,AG_L1,AG_L2,AG_Num,AG1_L1,AG1_L2,AG1_Num,timestamp_column_name_year,timestamp_column_name_month,timestamp_column_name_day,timestamp_column_name_minute
5,0.043142,0.003388,3.140213e-07,3.140213e-07,0.0,0.0,0.500000,0.0,0.0,0.0,...,0.166667,0.0,0.000200,0.000000,0.0,0.000100,0.0,0.0,0.0,0.271186
13,0.041868,0.008494,6.606712e-08,6.606712e-08,0.0,0.0,0.500000,0.0,0.0,0.0,...,0.000000,0.0,0.000601,0.500000,0.5,0.000100,0.0,0.0,0.0,0.237288
14,0.312802,0.077349,1.043652e-06,1.043652e-06,0.0,0.0,0.500000,0.0,0.0,0.0,...,0.000000,0.0,0.004604,0.000000,0.0,0.000601,0.0,0.0,0.0,0.474576
15,0.585786,0.632289,7.299649e-04,7.299649e-04,0.0,0.0,0.500000,0.0,0.0,0.0,...,0.166667,0.0,0.000100,0.000000,0.0,0.883896,0.0,0.0,0.0,0.237288
18,0.004807,0.328429,2.248285e-09,2.248285e-09,0.0,0.0,0.500000,0.0,0.0,0.0,...,0.000000,0.0,0.000601,0.000000,0.0,0.299369,0.0,0.0,0.0,0.338983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
461332,0.408916,0.000040,9.832393e-09,9.832393e-09,1.0,1.0,0.833333,0.0,0.0,0.0,...,0.333333,0.0,0.012111,0.500000,0.5,0.008107,0.0,0.0,1.0,0.881356
461335,0.000040,0.404882,1.374798e-07,1.374798e-07,1.0,1.0,0.833333,0.0,0.0,0.0,...,0.833333,0.0,0.021119,0.166667,0.0,0.000000,0.0,0.0,1.0,0.677966
461339,0.676619,0.680420,3.116757e-09,3.116757e-09,1.0,1.0,0.833333,0.0,0.0,0.0,...,0.000000,0.0,0.006206,0.666667,0.0,0.000300,0.0,0.0,1.0,0.576271
461340,0.000040,0.000334,4.257944e-09,4.257944e-09,1.0,1.0,0.833333,0.0,0.0,0.0,...,0.000000,0.0,0.529577,0.666667,0.0,0.016115,0.0,0.0,1.0,0.728814
461341,0.000040,0.000334,4.884542e-09,4.884542e-09,1.0,1.0,0.833333,0.0,0.0,0.0,...,0.000000,0.0,0.529577,0.666667,0.0,0.016115,0.0,0.0,1.0,0.576271

'\n\nThe predict_cols_scaled_df_y_test dataset: \n'

5         0
13        0
14        0
15        0
18        0
         ..
461332    0
461335    0
461339    0
461340    0
461341    0
Name: Is Laundering, Length: 115337, dtype: int64

0    115295
1        42
Name: Is Laundering, dtype: int64

# Balance the train dataset.

In [14]:
from imblearn.combine import SMOTEENN
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import EditedNearestNeighbours
from sklearn.utils import shuffle
from joblib import Parallel, delayed
import numpy as np
import pandas as pd

# Create a valid SMOTEENN instance with actual SMOTE
def create_smoteenn():
    return SMOTEENN(
        sampling_strategy='auto',
        random_state=42,
        smote=SMOTE(k_neighbors=3, n_jobs=-1),
        enn=EditedNearestNeighbours(n_neighbors=3, n_jobs=-1),
        n_jobs=-1
    )

# Process one batch safely
def process_batch(X_batch, y_batch, i):
    try:
        sme = create_smoteenn()
        X_res, y_res = sme.fit_resample(X_batch, y_batch)
        print(f"Batch {i+1} done")
        return X_res, y_res
    except Exception as e:
        print(f"Skipping batch {i+1}: {e}")
        return None

# Main function: parallel + SMOTEENN
def batchwise_smoteenn_fast(X, y, batch_size=200000, n_jobs=-1):
    # Optional shuffle to randomize order
    X, y = shuffle(X, y, random_state=42)

    # Convert to NumPy for slicing
    X_np = X.values if isinstance(X, pd.DataFrame) else X
    y_np = y.values if isinstance(y, pd.Series) else y

    num_rows = len(X_np)
    num_batches = (num_rows + batch_size - 1) // batch_size

    # Prepare batches
    batches = [
        (X_np[i * batch_size : min((i + 1) * batch_size, num_rows)],
         y_np[i * batch_size : min((i + 1) * batch_size, num_rows)], i)
        for i in range(num_batches)
    ]

    print(f"Starting parallel processing with {num_batches} batches...")

    # Run in parallel
    results = Parallel(n_jobs=n_jobs)(
        delayed(process_batch)(*args) for args in batches
    )

    # Filter out failed batches
    X_resampled_list = [r[0] for r in results if r is not None]
    y_resampled_list = [r[1] for r in results if r is not None]

    if not X_resampled_list:
        raise ValueError("All batches failed. Nothing to concatenate.")

    # Combine
    X_final = np.vstack(X_resampled_list)
    y_final = np.hstack(y_resampled_list)

    # Convert back to DataFrame/Series if needed
    if isinstance(X, pd.DataFrame):
        X_final = pd.DataFrame(X_final, columns=X.columns)
    if isinstance(y, pd.Series):
        y_final = pd.Series(y_final, name=y.name)

    print("All batches processed and combined.")
    return X_final, y_final

X_train, y_train = batchwise_smoteenn_fast(X_train, y_train, batch_size=200000, n_jobs=4)

X_train

Starting parallel processing with 2 batches...

/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(
/usr/local/lib/python3.10/site-packages/imblearn/over_sampling/_smote/base.py:345: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(

All batches processed and combined.

,From Bank,To Bank,Amount Received,Amount Paid,hour,day,weekday,month,Receiving Currency_Bitcoin,Payment Currency_Australian Dollar,...,AG_L1,AG_L2,AG_Num,AG1_L1,AG1_L2,AG1_Num,timestamp_column_name_year,timestamp_column_name_month,timestamp_column_name_day,timestamp_column_name_minute
0,0.000597,0.000597,1.404977e-06,1.404977e-06,0.782609,0.444444,0.000000,0.0,0.0,0.0,...,0.000000,0.000000,0.000901,0.000000,0.00000,0.000901,0.0,0.0,0.444444,0.033898
1,0.000040,0.000334,9.775577e-08,9.775577e-08,0.000000,0.888889,0.666667,0.0,0.0,0.0,...,0.000000,0.000000,0.397458,0.833333,0.00000,0.078170,0.0,0.0,0.888889,0.474576
2,0.183807,0.183807,5.188305e-05,5.188305e-05,0.652174,0.000000,0.500000,0.0,0.0,0.0,...,0.833333,0.500000,0.000100,0.833333,0.50000,0.000100,0.0,0.0,0.000000,0.711864
3,0.000329,0.000329,4.583905e-08,4.583905e-08,0.391304,0.777778,0.500000,0.0,0.0,0.0,...,0.000000,0.000000,0.000500,0.000000,0.00000,0.000500,0.0,0.0,0.777778,0.542373
4,0.191385,0.191953,1.412280e-10,1.412280e-10,0.956522,0.333333,1.000000,0.0,0.0,0.0,...,0.000000,0.000000,0.038134,0.000000,0.00000,0.479532,0.0,0.0,0.333333,0.474576
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691763,0.000186,0.343850,3.100065e-08,3.100065e-08,0.626514,0.555556,0.166667,0.0,0.0,0.0,...,0.333333,0.166667,0.005105,0.000000,0.00000,0.064025,0.0,0.0,0.555556,0.867464
691764,0.000186,0.204980,1.325163e-07,1.325163e-07,0.676347,0.530887,0.129664,0.0,0.0,0.0,...,0.000000,0.000000,0.000801,0.037003,0.00000,0.000489,0.0,0.0,0.530887,0.749652
691765,0.000186,0.309878,2.444572e-05,2.444572e-05,0.636052,0.111111,0.666667,0.0,0.0,0.0,...,0.333333,0.166667,0.005105,0.000000,0.00000,0.525912,0.0,0.0,0.111111,0.527329
691766,0.714418,0.423557,9.549303e-07,9.549303e-07,0.449202,0.543226,0.148172,0.0,0.0,0.0,...,0.536990,0.000000,0.081954,0.833333,0.03699,0.084634,0.0,0.0,0.543226,0.834270
691767,0.119963,0.117125,2.377088e-07,2.377088e-07,0.774652,0.181844,0.772767,0.0,0.0,0.0,...,0.121133,0.060567,0.002365,0.000000,0.00000,0.000764,0.0,0.0,0.181844,0.043115

In [15]:
display(y_train)
y_train.value_counts()

0         0
1         0
2         0
3         0
4         0
         ..
691763    1
691764    1
691765    1
691766    1
691767    1
Name: Is Laundering, Length: 691768, dtype: int64

0    345886
1    345882
Name: Is Laundering, dtype: int64

# Compute the weight to y_train as we already balanced it in the earlier code.

In [16]:
from sklearn.utils.class_weight import compute_class_weight

# numpy.ravel(a, order='C') : Return a contiguous flattened array.
# A 1-D array, containing the elements of the input, is returned. A copy is made only if needed.
y_train = y_train.values.ravel()

# https://scikit-learn.org/stable/modules/generated/sklearn.utils.class_weight.compute_class_weight.html
# sklearn.utils.class_weight.compute_class_weight(class_weight, *, classes, y)
# Returns: class_weight_vect : ndarray of shape (n_classes,) : Array with class_weight_vect[i] the weight for i-th class.
temp_compute_class_weight = compute_class_weight(class_weight="balanced", # class_weight : dict, “balanced” or None
                                                 classes=np.unique(y_train), # classes : ndarray
                                                 y=y_train) # y : array-like of shape (n_samples,)

# Classification and weighting.
tempResClassWeight = {tempIdx: tempData1 for tempIdx, tempData1 in zip(np.unique(y_train, 
                                                                                 return_index=False, 
                                                                                 return_inverse=False, 
                                                                                 return_counts=False, 
                                                                                 axis=None, 
                                                                                 equal_nan=True), 
                                                                      temp_compute_class_weight)}

# Show weight.
tempResClassWeight

{0: 0.9999942177480442, 1: 1.0000057823188255}

# So, now, Data Processing work over. It's the most important step. Otherwise, we won't get best results. Now, off to 5 models to test.

In [17]:
from sklearn.metrics import make_scorer, accuracy_score, precision_score, recall_score, roc_auc_score

# Source: https://scikit-learn.org/stable/modules/generated/sklearn.metrics.make_scorer.htmls
# sklearn.metrics.make_scorer(score_func, *, response_method='default', greater_is_better=True, **kwargs)
# Make a scorer from a performance metric or loss function.
# A scorer is a wrapper around an arbitrary metric or loss function that is called with the signature scorer(estimator, X, y_true, **kwargs).
# It is accepted in all scikit-learn estimators or functions allowing a scoring parameter.
# The parameter response_method allows to specify which method of the estimator should be used to feed the scoring/loss function.
# response_method{“predict_proba”, “decision_function”, “predict”} or list/tuple of such str, default=None
# metrics_score_list = {
#     # https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html
#     'accuracy_score' : make_scorer(accuracy_score),
#     # https://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_score.html
#     'precision_score' : make_scorer(precision_score),
#     # https://scikit-learn.org/stable/modules/generated/sklearn.metrics.recall_score.htmls
#     'recall_scores' : make_scorer(recall_score),
#     # https://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_auc_score.html
#     'roc_auc_score' : make_scorer(roc_auc_score),
# }

metrics_score_list = ['accuracy', # https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html
                      # https://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_score.html
                      'precision', 
                      # https://scikit-learn.org/stable/modules/generated/sklearn.metrics.recall_score.htmls
                      'recall', 
                      # https://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_auc_score.html
                      'roc_auc',
                      # https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html
                     'f1']

# Model-1: Neural Network (AUC ROC + Accurcay + F1)

In [18]:
from tensorflow.keras.models import Sequential
from scikeras.wrappers import KerasClassifier
from tensorflow.keras.layers import Dense, Dropout
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from tensorflow import keras
from sklearn.metrics import classification_report, roc_auc_score, accuracy_score, f1_score, precision_score, recall_score

# https://www.tensorflow.org/guide/keras/sequential_model
# https://keras.io/guides/sequential_model/
# https://faroit.com/keras-docs/1.0.1/getting-started/sequential-model-guide/
# https://adriangb.com/scikeras/stable/generated/scikeras.wrappers.KerasClassifier.html
# class scikeras.wrappers.KerasClassifier(model=None, *, build_fn=None, warm_start=False, random_state=None, optimizer='rmsprop', loss=None, metrics=None, batch_size=None, validation_batch_size=None, verbose=1, callbacks=None, validation_split=0.0, shuffle=True, run_eagerly=False, epochs=1, class_weight=None, **kwargs)
# You can also create a Sequential model incrementally via the add() method:
# model = keras.Sequential()
# model.add(layers.Dense(2, activation="relu"))
# model.add(layers.Dense(3, activation="relu"))
# model.add(layers.Dense(4))
def create_model(learning_rate=0.001):
    model = keras.Sequential()
    model.add(keras.layers.Dense(32, activation='relu', input_shape=(X_train.shape[1],)))
    model.add(keras.layers.Dense(16, activation='relu'))
    model.add(keras.layers.Dense(1, activation='sigmoid'))  # Binary classification
    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=learning_rate),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )
    return model

clf_Nun = KerasClassifier(model=create_model, 
                      verbose=0)


# estimator details for LogisticRegressions.
# https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html
# https://machinelearningmastery.com/grid-search-hyperparameters-deep-learning-models-python-keras/
pipeline = Pipeline([
    ('clf', clf_Nun)
])
# Inverse of regularization strength; must be a positive float.
# C : float, default=1.0
# param_grid : dict or list of dictionaries
param_grid = {
    'clf__model__learning_rate': [0.001,
                                  0.01],
    'clf__batch_size': [16, 
                        32],
    'clf__epochs': [10, 
                    20]
}

# https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html
# class sklearn.model_selection.GridSearchCV(estimator, param_grid, *, scoring=None, n_jobs=None, refit=True, cv=None, verbose=0, pre_dispatch='2*n_jobs', error_score=nan, return_train_score=False)
# clf_NuN_grid_search = GridSearchCV(estimator=pipeline,
#                                    param_grid=param_grid,
#                                    cv=3,
#                                    verbose=1,
#                                    error_score='raise'
#                                 )

clf_NuN_grid_search = GridSearchCV(
                    estimator=pipeline,
                    param_grid=param_grid,
                    scoring=metrics_score_list, 
                    refit=False,
                    cv=3,
                    verbose=1,
                    error_score='raise'
                )


# fit(X, y=None, **params)
clf_NuN_grid_search.fit(X_train, # X
                       y_train) # y

# cv_results_dict of numpy (masked) ndarrays : A dict with keys as column headers and values as columns, that can be imported into a pandas DataFrame.
tempResCV = clf_NuN_grid_search.cv_results_
print("\n The clf_NuN_grid_search's results are: \n", clf_NuN_grid_search.cv_results_)

# AOC-RUC
print("\n\n****************************************************************************************")
print("\nBASED ON LOGISTIC REGRESSION CLASSIFIER's BEST AUC-ROC PARAMETER:")
tempo_mapping_roc_auc = clf_NuN_grid_search.cv_results_['params'][tempResCV['mean_test_roc_auc'].argmax()]
print(f"\nThe Best Parameters for AUC-ROC:\n {tempo_mapping_roc_auc}")

2025-05-05 11:16:37.392760: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

Fitting 3 folds for each of 8 candidates, totalling 24 fits
Batch 2 done
Batch 1 done

 The clf_NuN_grid_search's results are:
 {'mean_fit_time': array([407.25160559, 481.69321394, 767.1517605 , 871.83747808,
       155.20891031, 161.35407988, 334.00685867, 349.48293106]), 'std_fit_time': array([  8.81683943,  30.44593699, 113.87253071, 114.75704288,
         7.47430918,   3.68024646,  17.25726775,  18.60583303]), 'mean_score_time': array([42.39313134, 41.38109875, 38.90424101, 33.771945  , 14.37571168,
       14.30198169, 15.61050367, 15.64076718]), 'std_score_time': array([ 4.48534453,  4.08595826, 11.99697853,  8.03617294,  0.62886514,
        0.3684314 ,  0.79544418,  1.2301823 ]), 'param_clf__batch_size': masked_array(data=[16, 16, 16, 16, 32, 32, 32, 32],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_clf__epochs': masked_array(data=[10, 10, 20, 20, 10, 10, 20, 20],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_clf__model__learning_rate': masked_array(data=[0.001, 0.01, 0.001, 0.01, 0.001, 0.01, 0.001, 0.01],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'clf__batch_size': 16, 'clf__epochs': 10, 'clf__model__learning_rate': 0.001}, {'clf__batch_size': 16, 'clf__epochs': 10, 'clf__model__learning_rate': 0.01}, {'clf__batch_size': 16, 'clf__epochs': 20, 'clf__model__learning_rate': 0.001}, {'clf__batch_size': 16, 'clf__epochs': 20, 'clf__model__learning_rate': 0.01}, {'clf__batch_size': 32, 'clf__epochs': 10, 'clf__model__learning_rate': 0.001}, {'clf__batch_size': 32, 'clf__epochs': 10, 'clf__model__learning_rate': 0.01}, {'clf__batch_size': 32, 'clf__epochs': 20, 'clf__model__learning_rate': 0.001}, {'clf__batch_size': 32, 'clf__epochs': 20, 'clf__model__learning_rate': 0.01}], 'split0_test_accuracy': array([0.97616115, 0.96092198, 0.98460037, 0.96700637, 0.96882345,
       0.97280454, 0.98260983, 0.97701548]), 'split1_test_accuracy': array([0.97636921, 0.95604734, 0.98017251, 0.9784942 , 0.97984726,
       0.97970415, 0.98363755, 0.96466874]), 'split2_test_accuracy': array([0.91228549, 0.93511833, 0.97416182, 0.92823162, 0.94835833,
       0.92244643, 0.96701491, 0.95764759]), 'mean_test_accuracy': array([0.95493862, 0.95069588, 0.9796449 , 0.95791073, 0.96567635,
       0.95831837, 0.9777541 , 0.96644394]), 'std_test_accuracy': array([0.03016043, 0.01119332, 0.00427782, 0.02150395, 0.01304649,
       0.02552121, 0.00760534, 0.00800593]), 'rank_test_accuracy': array([7, 8, 1, 6, 4, 5, 2, 3], dtype=int32), 'split0_test_precision': array([0.95719413, 0.94700672, 0.97070693, 0.94157495, 0.96704484,
       0.96846882, 0.96915683, 0.97435743]), 'split1_test_precision': array([0.95652716, 0.92217949, 0.96492937, 0.96244604, 0.9647042 ,
       0.96547661, 0.97396449, 0.94294289]), 'split2_test_precision': array([0.97903817, 0.93120224, 0.96601313, 0.94657959, 0.95900373,
       0.97042546, 0.97029435, 0.96038671]), 'mean_test_precision': array([0.96425316, 0.93346282, 0.96721648, 0.95020019, 0.96358426,
       0.96812363, 0.97113856, 0.95922901]), 'std_test_precision': array([0.01045813, 0.01026095, 0.00250746, 0.0088969 , 0.00337694,
       0.00203505, 0.00205149, 0.01285103]), 'rank_test_precision': array([4, 8, 3, 7, 5, 2, 1, 6], dtype=int32), 'split0_test_recall': array([0.99690357, 0.9764862 , 0.99935816, 0.99580204, 0.97072701,
       0.97743161, 0.99694694, 0.97981682]), 'split1_test_recall': array([0.99810051, 0.99615765, 0.9965653 , 0.9958454 , 0.9961403 ,
       0.99498673, 0.99384183, 0.98919285]), 'split2_test_recall': array([0.84261106, 0.93965861, 0.98290457, 0.90768817, 0.93676167,
       0.87145038, 0.96352802, 0.9546724 ]), 'mean_test_recall': array([0.94587171, 0.97076749, 0.99294268, 0.9664452 , 0.96787633,
       0.94795624, 0.98477226, 0.97456069]), 'std_test_recall': array([0.07301794, 0.02341742, 0.007189  , 0.0415475 , 0.02432489,
       0.05457048, 0.01507534, 0.01457476]), 'rank_test_recall': array([8, 4, 1, 6, 5, 7, 2, 3], dtype=int32), 'split0_test_roc_auc': array([0.99151778, 0.98636051, 0.99401501, 0.98117592, 0.99029092,
       0.99292726, 0.99351347, 0.99309753]), 'split1_test_roc_auc': array([0.99260796, 0.98315473, 0.99471941, 0.99086818, 0.99257924,
       0.99290211, 0.99558047, 0.98598226]), 'split2_test_roc_auc': array([0.99021112, 0.97286992, 0.99199531, 0.97417365, 0.9855686 ,
       0.98672133, 0.99152044, 0.98731955]), 'mean_test_roc_auc': array([0.99144562, 0.98079505, 0.99357658, 0.98207258, 0.98947959,
       0.99085023, 0.99353813, 0.98879978]), 'std_test_roc_auc': array([0.00097983, 0.00575471, 0.00115451, 0.00684494, 0.00291901,
       0.00291959, 0.00165759, 0.00308762]), 'rank_test_roc_auc': array([3, 8, 1, 7, 5, 4, 2, 6], dtype=int32), 'split0_test_f1': array([0.97664538, 0.96152056, 0.9848242 , 0.96792959, 0.96888242,
       0.97292957, 0.98285548, 0.9770795 ]), 'split1_test_f1': array([0.97687172, 0.95774213, 0.98049222, 0.9788609 , 0.98017026,
       0.98000957, 0.98380277, 0.96551432]), 'split2_test_f1': array([0.90571596, 0.93541132, 0.97438565, 0.92672603, 0.94775222,
       0.91827866, 0.96689935, 0.95752103]), 'mean_test_f1': array([0.95307769, 0.951558  , 0.97990069, 0.95783884, 0.96560164,
       0.9570726 , 0.97785253, 0.96670495]), 'std_test_f1': array([0.03348992, 0.01152116, 0.004282  , 0.02244814, 0.01343639,
       0.02758332, 0.00775472, 0.00802897]), 'rank_test_f1': array([7, 8, 1, 5, 4, 6, 2, 3], dtype=int32)}


****************************************************************************************

BASED ON LOGISTIC REGRESSION CLASSIFIER's BEST AUC-ROC PARAMETER:

The Best Parameters for AUC-ROC:
 {'clf__batch_size': 16, 'clf__epochs': 20, 'clf__model__learning_rate': 0.001}

NameError: name 'pipeline_NuN' is not defined

In [ ]:
tempo_mapping_roc_auc_fixed = {
    key.replace("clf_NuN__", "clf__"): val for key, val in tempo_mapping_roc_auc.items()
}

tempo_mapping_roc_auc_model = pipeline.set_params(**tempo_mapping_roc_auc_fixed).fit(X_train, y_train)
tempYPred = tempo_mapping_roc_auc_model.predict(X_test)
tempYPred_probability = tempo_mapping_roc_auc_model.predict_proba(X_test)[:,
                                                                     # Probability of the positive class (class 1)
                                                                     1]
# Classification report.
# sklearn.metrics.classification_report(y_true, tempYPred, *, labels=None, target_names=None, sample_weight=None, digits=2, output_dict=False, zero_division='warn')
print(classification_report(y_test, # y_true : 1d
                            tempYPred, # tempYPred : 1d
                            labels=None, 
                            target_names=None, 
                            sample_weight=None, 
                            digits=2, 
                            output_dict=False, 
                            zero_division='warn'))
# Get the roc_auc_score.
# https://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_auc_score.html
tmpAucRocScore = roc_auc_score(y_test, 
                               tempYPred_probability,
                               average='micro', 
                               sample_weight=None, 
                               max_fpr=None, 
                               multi_class='raise', 
                               labels=None)
print(f"\nThe AUC-ROC Score of the best model parameters:\n {tmpAucRocScore:.4f}")
# Test data calculations.
tmpAccuracyScore = accuracy_score(y_test, tempYPred)
print(f"\n[TEST DATA] The accuracy Score of the best model parameters:\n {tmpAccuracyScore:.4f}")
tmpF1Score = f1_score(y_test, tempYPred)
print(f"\n[TEST DATA] The F1 Score of the best model parameters:\n {tmpF1Score:.4f}")


# ACCURACY
print("\n\n****************************************************************************************")
print("\nBASED ON RLOGISTIC REGRESSION CLASSIFIER's BEST ACCURACY PARAMETER:")
tempo_mapping_accuracy = clf_NuN_grid_search.cv_results_['params'][tempResCV['mean_test_accuracy'].argmax()]
print(f"\nThe Best Parameters for ACCURACY:\n {tempo_mapping_accuracy}")

tempo_mapping_accuracy_fixed = {
    key.replace("clf__", "clf__"): val for key, val in tempo_mapping_accuracy.items()
}

tempo_mapping_accuracy_model = pipeline.set_params(**tempo_mapping_accuracy_fixed).fit(X_train, y_train)
tempYPred = tempo_mapping_accuracy_model.predict(X_test)
tempYPred_probability = tempo_mapping_accuracy_model.predict_proba(X_test)[:,
                                                                     # Probability of the positive class (class 1)
                                                                     1]
# Classification report.
# sklearn.metrics.classification_report(y_true, tempYPred, *, labels=None, target_names=None, sample_weight=None, digits=2, output_dict=False, zero_division='warn')
print(classification_report(y_test, # y_true : 1d
                            tempYPred, # tempYPred : 1d
                            labels=None, 
                            target_names=None, 
                            sample_weight=None, 
                            digits=2, 
                            output_dict=False, 
                            zero_division='warn'))
# Get the roc_auc_score.
# https://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_auc_score.html
tmpAucRocScore = roc_auc_score(y_test, 
                               tempYPred_probability,
                               average='micro', 
                               sample_weight=None, 
                               max_fpr=None, 
                               multi_class='raise', 
                               labels=None)
print(f"\nThe AUC-ROC Score of the best model parameters:\n {tmpAucRocScore:.4f}")
# Test data calculations.
tmpAccuracyScore = accuracy_score(y_test, tempYPred)
print(f"\n[TEST DATA] The accuracy Score of the best model parameters:\n {tmpAccuracyScore:.4f}")
tmpF1Score = f1_score(y_test, tempYPred)
print(f"\n[TEST DATA] The F1 Score of the best model parameters:\n {tmpF1Score:.4f}")


# F1
print("\n\n****************************************************************************************")
print("\nBASED ON LOGISTIC REGRESSION CLASSIFIER's BEST F-1 PARAMETER:")
tempo_mapping_f1 = clf_NuN_grid_search.cv_results_['params'][tempResCV['mean_test_f1'].argmax()]
print(f"\nThe Best Parameters for F1:\n {tempo_mapping_f1}")

tempo_mapping_f1_fixed = {
    key.replace("clf__", "clf__"): val for key, val in tempo_mapping_f1.items()
}
tempo_mapping_f1_model = pipeline.set_params(**tempo_mapping_f1_fixed).fit(X_train, y_train)
tempYPred = tempo_mapping_f1_model.predict(X_test)
tempYPred_probability = tempo_mapping_f1_model.predict_proba(X_test)[:,
                                                                     # Probability of the positive class (class 1)
                                                                     1]
# Classification report.
# sklearn.metrics.classification_report(y_true, tempYPred, *, labels=None, target_names=None, sample_weight=None, digits=2, output_dict=False, zero_division='warn')
print(classification_report(y_test, # y_true : 1d
                            tempYPred, # tempYPred : 1d
                            labels=None, 
                            target_names=None, 
                            sample_weight=None, 
                            digits=2, 
                            output_dict=False, 
                            zero_division='warn'))
# Get the roc_auc_score.
# https://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_auc_score.html
tmpAucRocScore = roc_auc_score(y_test, 
                               tempYPred_probability,
                               average='micro', 
                               sample_weight=None, 
                               max_fpr=None, 
                               multi_class='raise', 
                               labels=None)
print(f"\n[TEST DATA] The AUC-ROC Score of the best model parameters:\n {tmpAucRocScore:.4f}")
# Test data calculations.
tmpAccuracyScore = accuracy_score(y_test, tempYPred)
print(f"\n[TEST DATA] The accuracy Score of the best model parameters:\n {tmpAccuracyScore:.4f}")
tmpF1Score = f1_score(y_test, tempYPred)
print(f"\n[TEST DATA] The F1 Score of the best model parameters:\n {tmpF1Score:.4f}")

              precision    recall  f1-score   support

           0       1.00      0.98      0.99    115295
           1       0.00      0.05      0.00        42

    accuracy                           0.98    115337
   macro avg       0.50      0.52      0.50    115337
weighted avg       1.00      0.98      0.99    115337


The AUC-ROC Score of the best model parameters:
 0.7191

[TEST DATA] The accuracy Score of the best model parameters:
 0.9828

[TEST DATA] The F1 Score of the best model parameters:
 0.0020


****************************************************************************************

BASED ON RLOGISTIC REGRESSION CLASSIFIER's BEST ACCURACY PARAMETER:

The Best Parameters for ACCURACY:
 {'clf__batch_size': 16, 'clf__epochs': 20, 'clf__model__learning_rate': 0.001}

In [ ]:
pd.Series(y_test).value_counts()

In [21]:
print(tempo_mapping_roc_auc_fixed.keys())

dict_keys(['clf_NuN__batch_size', 'clf_NuN__epochs', 'clf_NuN__model__learning_rate'])